# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]

